apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshort-deployment
  labels:
    app: urlshort
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshort
  template:
    metadata:
      labels:
        app: urlshort
    spec:
      containers:
        - name: urlshort
          image: urlshort:local
          ports:
            - name: urlshort
              containerPort: 8000
              protocol: TCP
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: urlshort-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: urlshort-configmap
                  key: REDIS_PORT
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "64Mi"
