apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshort-deployment
  labels:
    app: urlshort
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshort
  template:
    metadata:
      labels:
        app: urlshort
    spec:
      containers:
        - name: urlshort
          image: urlshort:local
          ports:
            - name: urlshort
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: urlshort-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: urlshort-configmap
                  key: REDIS_PORT
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "100m"
